In [1]:
import numpy as np

In [1]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
import numpy as np
data = np.random.randint(0,100,(10,2))
data

array([[77, 31],
       [30,  7],
       [94, 98],
       [43, 27],
       [41, 71],
       [47, 63],
       [41, 86],
       [11, 32],
       [67, 81],
       [85, 96]])

In [4]:
scaler_model = MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [6]:
scaler_model.fit(data)#allows model to learn, the min and max value

MinMaxScaler()

In [9]:
scaler_model.transform(data)#min becomes, 0 and max becomes 1
#divides each column value by max value

array([[0.79518072, 0.26373626],
       [0.22891566, 0.        ],
       [1.        , 1.        ],
       [0.38554217, 0.21978022],
       [0.36144578, 0.7032967 ],
       [0.43373494, 0.61538462],
       [0.36144578, 0.86813187],
       [0.        , 0.27472527],
       [0.6746988 , 0.81318681],
       [0.89156627, 0.97802198]])

In [10]:
scaler_model.fit_transform(data)

array([[0.79518072, 0.26373626],
       [0.22891566, 0.        ],
       [1.        , 1.        ],
       [0.38554217, 0.21978022],
       [0.36144578, 0.7032967 ],
       [0.43373494, 0.61538462],
       [0.36144578, 0.86813187],
       [0.        , 0.27472527],
       [0.6746988 , 0.81318681],
       [0.89156627, 0.97802198]])

In [15]:
import pandas as pd
myData=np.random.randint(0,101,(50,4))
data = pd.DataFrame(data = myData,columns=['f1','f2','f3','label'])
#myData
data

    f1   f2  f3  label
0   78   79  11     81
1   70  100  34      7
2   17   12  13     41
3   40    5  87     45
4    6   31  53     74
5   95   16  32     39
6   15   40  76     21
7   73   49  85     87
8   64   10  54     15
9   28   39  10     93
10  91   85  94     66
11  38   28  19     33
12  90   29  50     22
13  64   98  85     40
14  87   92  81     17
15  84   52  72      8
16  27   74  24     44
17  60   81  84     66
18  91   81  32     68
19  46   55  86     84
20  95   60  28     21
21  10   33  88     90
22  71    6  97     38
23  52   84   0     51
24  57   57  18     72
25  28   60  31     99
26  51   78  84      0
27  96   98  91     43
28  99   47  50     60
29  98   62  10     96
30  50   49   7     60
31  56   42  41     39
32  73   40  27      2
33  37   37  15     47
34  99   92  95     31
35  75   21  79     30
36  11   28  51     73
37  12   25  76     18
38  46    2  13     15
39  72   28  48     18
40  57   80  55     80
41  22    0  64     85
42  50   82  54     50
43  10   30  96     26
44  63   60  82     59
45  46   89  37     69
46  40   11  80     59
47  80   66  77     93
48  45   32   5     79
49  67   33  64     29

In [18]:
#split into training and test data
X = data[['f1','f2','f3']]
X

    f1   f2  f3
0   78   79  11
1   70  100  34
2   17   12  13
3   40    5  87
4    6   31  53
5   95   16  32
6   15   40  76
7   73   49  85
8   64   10  54
9   28   39  10
10  91   85  94
11  38   28  19
12  90   29  50
13  64   98  85
14  87   92  81
15  84   52  72
16  27   74  24
17  60   81  84
18  91   81  32
19  46   55  86
20  95   60  28
21  10   33  88
22  71    6  97
23  52   84   0
24  57   57  18
25  28   60  31
26  51   78  84
27  96   98  91
28  99   47  50
29  98   62  10
30  50   49   7
31  56   42  41
32  73   40  27
33  37   37  15
34  99   92  95
35  75   21  79
36  11   28  51
37  12   25  76
38  46    2  13
39  72   28  48
40  57   80  55
41  22    0  64
42  50   82  54
43  10   30  96
44  63   60  82
45  46   89  37
46  40   11  80
47  80   66  77
48  45   32   5
49  67   33  64

In [20]:
y=data['label']
y

0     81
1      7
2     41
3     45
4     74
5     39
6     21
7     87
8     15
9     93
10    66
11    33
12    22
13    40
14    17
15     8
16    44
17    66
18    68
19    84
20    21
21    90
22    38
23    51
24    72
25    99
26     0
27    43
28    60
29    96
30    60
31    39
32     2
33    47
34    31
35    30
36    73
37    18
38    15
39    18
40    80
41    85
42    50
43    26
44    59
45    69
46    59
47    93
48    79
49    29
Name: label, dtype: int32

from sklearn.model_selection import train_test_split

In [23]:
train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.3, random_state=42)
#test size, 30% of data is being considered into test 
#random state, is for repeatibility, like same random numbers we get when we use seed

In [28]:
X_train.shape

(35, 3)

In [29]:
X_test.shape

(15, 3)

In [30]:
#we would put the training sets for X_train,y_train, and model will understand, how the x_trian features are predicting the y_train labels

once we, have this, we can evaluate the model  by feeding it using x_test data, and we can predict the labels .

for full evaluation,  we will compare the predicted values to true y_test values

scikit learn is its own machine learning library for python, but doesnt support, deep neural networks, that Tensorflow can do